### ISSUE TITLE
Update finite fault property names and content paths

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1192]
In the finite fault component:
https://github.com/usgs/earthquake-eventpages/blob/master/src/app/finite-fault/finite-fault/finite-fault.component.html

Proposed contents and properties are on this page:
https://github.com/hschovanec-usgs/finite-fault-product/blob/master/docs/web_product.md

Update "" content to "analysis.html"
    Add `<h3>Scientific Analysis</h3>` header before shared-text-product.
    When content does not exist, output "Not available yet."

Update "nump1" property to "number-pwaves"
Update "nums1" property to "number-shwaves"
Update "numlow1" property to "number-longwaves"
Update "lon1" property to "longitude"
Update "lat1" property to "latitude"
Update "depth1" property to "depth"

Update "strike11" property to "model-strike"
Update "dip11" property to "model-dip"
Add ", rake = " with "model-rake" property following strike, dip.
> @hschovanec-usgs : is this correct to use the `model-` properties?  what are you using in *eventsourcecode*.html?

Update "moment1" property to "scalar-moment"
Update "magnitude1" property to "derived-magnitude"

Update "cross-section.png" content to "slip.png"
Update "map.png" content to "basemap.png"
Update "moment-rate.png" content to "moment_rate.png"

**Comment by jmfee-usgs** [comment]
Example events where finite-fault products that have been updated
us1000dyad
usp000714t
us10004u1y - two finite-fault products

**Comment by hschovanec-usgs** [comment]
@jmfee-usgs I believe that you are referencing the **Result** section. 

For a single segment model, using the model- properties is fine, because there is only one strike/dip line in the [html](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/1000dyad/1000dyad.html#L25). There is also only the [mechanism line](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/1000dyad/1000dyad.fsp#L8), and no individual segment strike/dip parameters. Because of this, segment-1- properties and model- properties are identical.

For a model with multiple segments there are specified strike/dip specified for each segment ([segment 1](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/000714t/p000714t.fsp#L52) and [segment 2](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/000714t/p000714t.fsp#L168)) as well as the [mechanism line](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/000714t/p000714t.fsp#L8). The html reflects this as a [table](https://github.com/hschovanec-usgs/finite-fault-product/blob/master/tests/data/products/000714t/000714t.html#L32-L37). I used the segment properties to generate the table.

**Comment by jmfee-usgs** [comment]
@hschovanec-usgs : so it sounds like we should always show the table, and list the one or multiple segments?
