### ISSUE TITLE
Implement finite-fault overlay using FFM.geojson

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1193]
- Use feature properties "fill", "fill-opacity", "stroke-width" to style geojson layer.  May need to override fill-opacity...

- Show popup with other properties:
    "sf_moment" => sub fault moment
    "slip" (meters)
    "rise" (meters)
    "trup" (seconds)
    "rake" (degrees)

- Integrate into interactive map
- If there is time, replace the slip.png content with a non-interactive map linking to interactive map.

**Comment by jmfee-usgs** [comment]
Example events where finite-fault products that have been updated
us1000dyad
usp000714t
us10004u1y - two finite-fault products

**Comment by ehunter-usgs** [comment]
Do we have a legend for this overlay?

**Comment by jmfee-usgs** [comment]
@hschovanec-usgs can comment, I think the scale is variable depending on the model...  We at least display values in popups for now, and can work on adding the legend later.

**Comment by cswilson-usgs** [comment]
Is this implemented on the old pages or is it a new feature?

**Comment by jmfee-usgs** [comment]
New feature.

**Comment by cswilson-usgs** [comment]
Is the scientific/engineering notation (it comes that way from FFM.geojson) ok instead of showing a HUGE number, or do we just want to show the actual whole number with commas for the sub-fault moment?

Also is the 'm' ok for the rest of the numbers for meters?
![Screen Shot 2018-09-26 at 2.27.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2926250ae6a400118ca8f8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f56b7191a37af1102c4f5c565ecc3c4a4356bcbbd671f3e57862804e0ee984690c72c43819adecd049b600ee208b48d4e5ee824ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ce84456a314336be0722431.png)

**Comment by ehunter-usgs** [comment]
@jmfee-usgs in response to your first comment,
```
"sf_moment" => sub fault moment
"slip" (meters)
"rise" (meters)
"trup" (seconds)
"rake" (degrees)
```
Is there any additional explanations for these values? Mainly for "trup"?
