### ISSUE TITLE
Add Legends to Interactive Map

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1247]
We are missing legends for some overlays.
 - landscan population
 - shakemap stations
 - shakemap contours
 - DYFI geocoded area

**Comment by emartinez-usgs** [comment]
**Comments**
- Landscan legend still not displayed.
- Not sure layer title `Landscan Population` is best. Fine to reference Landscan in attribution, but I would suggest layer toggle as "Population Density" or similar.
- Not seeing DYFI layers or legends at all.
- Sometimes `legends` is initialized to null, other times to an empty array. Be consistent. If initializing to an empty array, simply push legends into this array rather than re-initializing the object itself.
- Layers appear in different orders depending on how map is loaded. (1) Load executive page, refresh, then click interactive map. View layer control ordering. (2) Load interactive map, refresh. View layer ordering. Why is this different?
- Alphabetize importa in ground-failure.module.ts

**Comment by ehunter-usgs** [comment]
Still have not finished these parts:
	•	Not seeing DYFI layers or legends at all. (waiting on #1242)
	•	Layers appear in different orders depending on how map is loaded. (1) Load executive page, refresh, then click interactive map. View layer control ordering. (2) Load interactive map, refresh. View layer ordering. Why is this different? (Looking into this)
