### ISSUE TITLE
Fix Origin Time on Metadata tab

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1272]
Not formatted correctly,

https://earthquake.usgs.gov/beta/earthquakes/eventpage/us2000cmy3/shakemap/metadata

**Comment by emartinez-usgs** [comment]
- Requires better unit tests for these new cases (string, string-like number, number, date).
- Would like to see better method documentation.
- Use specific type(s) on input/output (i.e. not `any`).

**Comment by dslosky-usgs** [comment]
@emartinez-usgs thanks for the feedback; does it need to convert all those data types (string, string-like number, number, date)? I think the only ones we're using this pipe for are shakemap timestamps (strings) and OAF which uses milliseconds since epoch; I'm putting together some tests for those right now.

**Comment by emartinez-usgs** [comment]
It's fair to test what we might expect to receive. No need to test everything, but handle errors gracefully.
