### ISSUE TITLE
PAGER pending on beta pages

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/earthquake-eventpages#1282]
The card for PAGER on the beta pages displayed the alert level histograms while the alert level was pending. This behavior is incorrect and needs to be modified so that the beta pages perform the same as the current webpage during a pending alert.

<img width="1410" alt="screen shot 2018-09-11 at 11 34 56 pm" src="https://user-images.githubusercontent.com/26940012/45452301-d8019000-b69a-11e8-92af-509c39d89e33.png">

**Comment by emartinez-usgs** [comment]
@mhearne-usgs @kmarano-usgs 
Can one of you send a "pending" PAGER product to an older event on our dev systems? We will need the latest PAGER product to be a pending status in order to develop and verify this fix. Please comment with an event id we can use for development/testing.

Developers - 
When developing, please be sure the PAGER page also behaves similar to existing event pages when the PAGER product is still pending.

**Comment by mhearne-usgs** [comment]
Using the product Kristin found - us2000hd8v.  Just sent.

**Comment by mhearne-usgs** [comment]
"[receiver_socket] received product 'urn:usgs-product:us:losspager:us2000hd8v:1536872178684'
