### ISSUE TITLE
Add handling for ShakeMap offshore events

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1391]
For offshore events they send a "-", please handle this.

**Comment by llastowka-usgs** [comment]
I think bruce knows more, but for offshore events somewhere they send a hyphen and the code expects a 1-12...  That is all I know!

**Comment by cbworden** [comment]
It happens if there is no land. In that case the max_<IMT> values in the json have no value (because they are max value on land). In those cases we use '--' to indicate no value. But in the corresponding email thread, @jmfee-usgs is suggesting that we make the values null rather than ascii. That's easy enough, just let me know if that's what everybody wants.

**Comment by dslosky-usgs** [comment]
Null values are a good idea and will be rendered as '-' on the event page

**Comment by cswilson-usgs** [comment]
Trying to find an example event, I'm currently using us2000hdy6. Will these properties be in the overall 'product' json, or are they in one of the json files under the 'contents' property?

**Comment by cbworden** [comment]
I just reran event us1000h8ar with ShakeMap v4 (look for the product code that ends in "_sm4" on the dev system). The parameters in info.json are in the "ground_motions" section under "max" for each parameter; they are now null rather than '--'. Also, those parameters are sent as properties via pdl where they have a value of None (e.g., --property-maxmmi=None).

**Comment by dslosky-usgs** [comment]
Those null values will definitely make things easier, but I think for backwards compatibility we'll still need to handle '--'... We could handle this in the template, or via pipe, or by adding to the [translate function](https://github.com/usgs/earthquake-eventpages/blob/9b21a1449583b26f9d214dd6c8bf257382ce9dfa/src/app/core/metadata.service.ts#L86) on the metadata-service... that function is primarily for turning some objects into arrays for display purposes; maybe it should be a pipe anyway?

**Comment by cswilson-usgs** [comment]
Pipes are cacheable, and hence good

**Comment by ehunter-usgs** [comment]
@dslosky-usgs could you review the PR for this ticket? I am a little confused by this discussion, and think you would have a better idea of a proper solution.
