### ISSUE TITLE
FFM get to interactive map from page?

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1395]
On the FF page, do we want a way to get to interactive map from FF module? either a view on map button or click on one of the figures to get to map? @ghayes-usgs ? Others?

**Comment by jmfee-usgs** [comment]
The "surface projection" map is the most similar to what is shown on the interactive map (and could potentially be a non-interactive but dynamic map).  We also need to sort out the legend.

@ghayes-usgs : do you have thoughts on where/how to link to the map?  Ground Failure has buttons, but mainly because they do not yet show maps.  We could link from the image, or link from the image and add text to make it more obvious, or?  btw, the updated products look great

**Comment by ghayes-usgs** [comment]
Linking from the surface projection map would be great, as long as we could add a note indicating that was an option ("click on image to access interactive map", or similar).
I think the appearance of the FF on the interactive map needs a little work, too. As Jeremy indicated, a legend is needed. I think the sub-fault outlines are a little too dark (though I recognize this is exacerbated in this case because of the steep dip and hence small size of the sub-faults in map view). I think it'd also be nice if the sub-faults could have some transparency, particularly if they have low/zero slip.

**Comment by llastowka-usgs** [comment]
Clicking on the surface map is maybe not obvious. Could have button like on groundfailure product that says view in interactive map?  on interactive map? If there is time in 1.16 try some thing out.
