### ISSUE TITLE
update navigation for deleted events

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1523]
Most of the pages in the navigation go nowhere:
https://earthquake.usgs.gov/earthquakes/eventpage/nc72457111/executive

Should we allow access to limited information (beyond header), like a map?
Hide links in nav that do not make sense.

**Comment by cswilson-usgs** [comment]
I'm thinking the only relevant information may be just the interactive map link. Since the interactive map opens in full screen, and closing it routes back to the executive page, is it safe to assume that really the only valid link would be the interactive map link?


![Screen Shot 2018-12-19 at 10.58.07 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2926250ae6a400118ca8f8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455fa6b7191a379ef0c2e59415f49bc30254d58eeb9cb74fce36f34985619e8d5385b27c03f14a4b9d64de908bb748b4f82e7efd844c6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe44f51a6103562e075376e0a.png)

**Comment by llastowka-usgs** [comment]
I don't even think you need that... because there will be nothing on it?

**Comment by cswilson-usgs** [comment]
I just noticed that. I have simply hidden the entire side-nav except for the blue links that lead back to USGS pages.

**Comment by cswilson-usgs** [comment]
![Screen Shot 2018-12-19 at 11.19.37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2926250ae6a400118ca8f8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455fa6b7191a379ee0c2a58415c49bc30254d58eeb9cb74fce36f34985619e8d5385b27c03f14a4b9d64de908bb748b4f82e7efd844c6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe44f51a7153767e174356e0a.png)
