### ISSUE TITLE
DYFI Layers on Interactive Map

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#223]
Update the interactive map to include:
- "DYFI Responses (zip code)" layer
- "DYFI Responses (10km)" layer
- "DYFI Responses (1km)" layer

These are in addition to the existing DYFI layer. Each of these layers should be mutually exclusive. For the zip codes layer, the marker should be a circle whose radius is directly related to the corresponding zip code population. Note: The files with data for these layers may or may not exist and each should be checked independently.

**Comment by llastowka-usgs** [comment]
@vinceq-usgs Vince - I don't know all the details but we don't have all of the data. Like we don't have a center point for the  zip codes polygons. Also I am not sure if we are even getting all of these layers... I don't have all the details but just want to start the discussion. 
Thanks!

**Comment by vinceq-usgs** [comment]
The interactive map is already plotting the file dyfi_geo.geojson on the Interactive Map. This file is either 1 km aggregated, or 10km aggregated, depending on the size of the event.

This issue is for plotting another dataset: dyfi_geo_1km.geojson. My rule for generation is: 
1. The original dyfi_geo.geojson will always exist, either a 10km or 1km dataset.
2. If the original map is 10km, then I create an extra dyfi_geo_1km.geojson.

This system is open for discussion (e.g. would it be easier if I rename to dyfi_geo_1km and dyfi_geo_10km, always create both files no matter what, etc.) 

As for the ZIP codes, there's a few options:
1. Currently: I am already creating a dyfi_zip.geojson file with the ZIP polygons and city points in it.
2. I give you a dataset of all the ZIP codes I have and put it in a static webserver. Whenever DYFI has a ZIP polygon to plot, the map can call from that. This will save file/transfer space... BUT I will need to periodically update the ZIP codes.
3. I've talked to Greg about setting up a ZIP code webservice that we can use, but that will take some time to set up.
4. Eric mentions plotting a point instead of a polygon. Now some of the data in the dyfi_zip.geojson are actually city points (and the population is one of the properties of that point, so the size of those cities should be population-based.) However, plotting ZIP *polygons* as points is not sufficient.

**Comment by llastowka-usgs** [comment]
I talked to dave and he says that the zip code plotting is a lower priority, which is good because to me sounds like no real answer there yet.   Sounds like a few things are possible on the different resolutions but not sure if we can decide the best way forward before the holidays.

**Comment by vinceq-usgs** [comment]
Lynda, I think the easiest right now would be to plot dyfi_geo_1km.geojson, if it exists. The geo_1km file is functionally equivalent to the regular dyfi_geo.geojson file.

**Comment by jmfee-usgs** [comment]
Predictable is best.  I would suggest always using the _1km and _10km file names, and only generating the files when they make sense.  We can look for one or the other, and make whichever you prefer the default.  We will need to make changes to support new file names, so please coordinate any changes you make.

**Comment by vinceq-usgs** [comment]
Okay. I also want to make the system compatible with previous systems, in which the dyfi_geo.geojson file always exists. There isn't a reason to pick a "default" right now since it's always a user-selected option on the Interactive Map. 

How about this logic:
1. Always plot dyfi_geo_1km.geojson, if it exists
2. Always plot dyfi_geo_10km.geojson if it exists
3. plot dyfi_geo.geojson, if neither 1. or 2. exist

**Comment by jmfee-usgs** [comment]
Should 1 and 2 be swapped (show the 10km grid if it exists, then fall back to 1km, since that implies a larger event)?

**Comment by vinceq-usgs** [comment]
Are we talking about turning something on by default? Then yes you are right, 10km preferred. But on the Interactive Map, both should always be available and selectable.

**Comment by jmfee-usgs** [comment]
I believe we're planning to enable the layer automatically when a user clicks the static image on the DYFI page

**Comment by vinceq-usgs** [comment]
In that case, the 10km should be preferred, then 1km, then the plain "dyfi_geo.geojson".
