### ISSUE TITLE
Customize sharing links

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#265]
Look into making this module specific, or just improving the "shared" information in general (maybe a quick summary?).

> He’s right.  The old event pages include the appropriate image when you “Share on Facebook”, but the current event pages don’t include an image.  You can test this with the two URLs he provides below.
> 
> I want to enter an issue for this in github, but I don’t know if the fix is a hazdev-template, earthquake-website, or earthquake-eventpages issue.
> 
> Here is pertinent info: https://developers.facebook.com/docs/sharing/web
> 
> -Lisa
> —
> 
> > I went online to use the "Did You Feel It" page after a local quake and discovered the USGS is eliminating the page I've always used. (http://earthquake.usgs.gov/earthquakes/dyfi/events/nc/72569541/us/index.html)
> > I would not mind except that the replacement page does not allow me to show a thumbnail map when I post it to facebook. There's just this dull text box in facebook when I link to the replacement USGS page with the map. (http://earthquake.usgs.gov/earthquakes/eventpage/nc72569541#impact_dyfi:us_nc72569541)
> > I can think of lots of reasons it is better to have an eye-catching image in a facebook link, but am finding it tough to imagine why the new page's designers have opted not to do that.
> > 
> > Any chance this will change before the old page completely goes away? Please!

**Comment by ehunter-usgs** [comment]
I didn't know much about Facebook and how "sharing" works, so i was interested in this ticket.

It sounds like there is a "facebot" that crawls the site looking for meta tags using the Open Graph  protocol (http://ogp.me/). Without these tags defined Facebook still does a fine job scraping the page title and general site description.

There is a cool tool you can use to preview what the shared link will look like on FB, use the link below:

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fearthquake.usgs.gov%2Fearthquakes%2Feventpage%2Fus10004u1y%23origin

The end result is slightly different than the link above would suggest (see attached photo). Once i actually shared the post FB also tried to add the USGS icon to the post. Unfortunately the logo is white and therefore does not appear on the white FB background.

I'd say there are three options at this point:
- Do nothing.
- Add a meta tag (og:image) to the template that has a more visible USGS icon
- Dynamically update meta tags for the event pages when content loads from general summary, dyfi, shakemap, pager, etc so that when the user goes to share pages these images appear in the share preview.

**Comment by ehunter-usgs** [comment]
This is what the shared event actually looked like on my FB page.
![screen shot 2016-06-20 at 4 36 47 pm](https://cloud.githubusercontent.com/assets/1932750/16212708/d371c142-3706-11e6-8c93-43c8e2c8a172.png)

**Comment by jmfee-usgs** [comment]
I'd vote for adding all the `og:___` meta tags listed as warnings on the FB page.  We may also want to consider that for other pages besides event pages, and possibly address in the template?

**Comment by ehunter-usgs** [comment]
@jmfee-usgs if we wanted to address all the `og:*` meta tags listed as warnings...

Are you in favor of adding one image (the usgs icon), or many images? For instance, the eventpages would we add all images from the different product creators as they are loaded dynamically?

**Comment by emartinez-usgs** [comment]
I feel a USGS logo is not so much more useful than not having an image. For that reason, I would leave the og:image tag to individual pages and not set it at a template level. Some of the `og:*` properties could be set at a template level, but how can we do this an still allow individual pages to override it? When to these `og:*` tags get evaluated? Can we add/edit them in Javascript?

**Comment by jmfee-usgs** [comment]
It sounds like they are scraping the html, so they would most likely need to be output using the `$HEAD` template variable.  I'd say let's sort it out for the event pages first, and decide what to do for other pages after we have it working.

**Comment by ehunter-usgs** [comment]
I can't find a consistent answer to @emartinez-usgs, it sounds like their either use the largest image from the `og:image` tag, or they use to last one added to the page head.

**Comment by ehunter-usgs** [comment]
proposed PR:
https://github.com/usgs/hazdev-template/pull/254

I found out two more things:
- You cannot use SVG images
- You cannot use relative links to images

**Comment by ehunter-usgs** [comment]
I didn't realize that earthquake-website would override _config.inc.php, where should i be adding these meta tags for facebook?

**Comment by jmfee-usgs** [comment]
Add these to the event page src/htdocs/index.php, at the end of the `$HEAD` content.
