### ISSUE TITLE
create ShakeMapView class

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#294]
in js/shakemap folder

Should render contents of ShakeMap details page, from existing page https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/modules/impact/ShakeMapPage.js#L96

The only exception is the stationlist details, which will be implemented in the ShakeMapStationListView class (separate issue).

**Comment by jmfee-usgs** [comment]
Change order of tabs:

- Intensity
- PGA
- PGV
- Station List
- Info (separate issue), create placeholder for now
- Uncertainty
- PSA (combine all images in one tab, using headers.  order: 0.3, 1.0, 3.0)

**Comment by emartinez-usgs** [comment]
Code needs a rebase...

Miscellaneous
- Example navigation should put ShakeMapView in the "Impact" section similar to what is done on the event page itself.
- Error on example page should not claim an error occurred with the "download view."
- Browserify ALL_CLASSES should be alphabetized.
- Should include unit tests for each public method of the class.

ShakeMapView
- Alphabetize methods
- Adding a class to `el` should occur during initialization, not during render method.
- Try working the the `Product` object itself rather than converting it to a JS object.
- Probably do not want to call `render` when creating the station list view initially. The `content` method for that tab should probably call render, in this way we get deferred loading. This may depend on the `ShakeMapStationListView` implementation.
- Info tab title should just be "Info" (per ticket)
- PSA image titles should be "PSA VALUE UNITS (%g)" (i.e. a space between value and units).
- Hoist variable declarations e.g. `for (var i = 0; ...)`
- Check for PSA images should check for actual PSA files, not the PGV file. Probably need to build up an array of of existing image information, the pass it to a single `createPSATabListImages` call if said array is non-empty.

**Comment by emartinez-usgs** [comment]
- Needs a `destroy` method.
- Move render method into alphabetical order.
- Use `Product.isDeleted` method.
- Try to only call `getContent` once per content item...
```JS
    // Intesity Image
    intensityContent = shakemap.getContent('download/intensity.jpg');
    if (intensityContent) {
      _this.tablist.addTab({
        title: 'Intensity',
        content: _this.createTabListImage(intensityContent)
      });
    }
```

**Comment by emartinez-usgs** [comment]
- Need to destroy ShakeMapStationList
- Need to destroy TabList
