### ISSUE TITLE
create a NearbyPlacesView class

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#341]

**Comment by ehunter-usgs** [comment]
Please rebase.

**Comment by jdbrown-USGS** [comment]
- Rebased
- Uses product rather than contentView in example.

**Comment by emartinez-usgs** [comment]
- Rebase
- Make `NearbyPlacesView` extend the `ProductView`
- Do not try to integrate view into `GeneralSummaryModule`
- Use the actual nearby-cities.json file associated with the event (on the example page)

**Comment by jmfee-usgs** [comment]
please rebase

**Comment by jmfee-usgs** [comment]
- As a ProductView, the model should be the nearby-cities product; and the view should internally get the nearby-cities.json content.
- Remove the "Nearby Places" header, the module that uses this View can create it's own header (if there's a header at all).
- Make a better onError message, instead of displaying status.  Make this a configurable parameter, with a default of "Error loading nearby places"
- Add method/class comments
