### ISSUE TITLE
Add/move title on origin, moment-tensor, focal-mechanism modules

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#448]

**Comment by emartinez-usgs** [comment]
- Need to keep the override for `getTitle` on FocalMechanismView in, otherwise errors are generated.
  - Can probably return an empty documentFragment.
- The `h3` with the module name should be generated regardless of whether getProductHeader returns anything (which it always does).
- The `h3` content should come from _this.TITLE rather than being hard-coded.
