### ISSUE TITLE
ShakeMapPin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#549]
Create product-specific pin for ShakeMap products.

**Comment by emartinez-usgs** [comment]
- Remove MMI bubble from content area.
- Use the TV map as the map image.

**Comment by emartinez-usgs** [comment]
- Add MMI impact bubble to header section.

**Comment by jmfee-usgs** [comment]
Use "pin-thumbnail.png" if content exists in ShakeMap product, otherwise use existing TV map image.

**Comment by jmfee-usgs** [comment]
Use the product method "getProperty", instead of getting properties from the model, to be more null safe.

- Add destroy method to free _formatter reference
- consider making _formatter a property on _this in case this pin were ever subclassed
- `tvMap` variable name is a little misleading
- _could_ subclass renderPinHeader method using Util.compose, followed by insertAdjacentHTML to add bubble to header; instead of reimplementing header logic from parent class.
