### ISSUE TITLE
Impact Pin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#586]
Create an impact pin that links to the impact ImpactSummaryModule page. This pin should have impact bubbles for DYFI, SM and PAGER products. This pin should be the first pin on the ExecutiveSummary page.

**Comment by jmfee-usgs** [comment]
Attribution ("Contributed by" in the footer) is incorrect, and should be based on the DYFI, ShakeMap, and PAGER products instead of the preferred origin.

I also think this pin shouldn't exist, we already have pins for all the information being summarized in this pin so it seems redundant.  We do not have a similar Scientific Summary pin, for similar reasons: the scientific information is already being summarized by other pins.  I recommend moving the summary bubbles to the corresponding product pins.

**Comment by jmfee-usgs** [comment]
having multiple products as a source for attribution seems like a common use case, recommend moving logic into Attribution class, maybe "getProductsAttribution", then pass array of products to method in ImpactPin

**Comment by emartinez-usgs** [comment]
Impact pin is deprecated.
