### ISSUE TITLE
Implement QuakemlService

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#774]
For parsing quakeml messages, will be used by  #752 and #753

**Comment by emartinez-usgs** [comment]
- Coverage
  - Some branch/statement coverage in event.ts

- Coding standards
  - Whitespace between function name and opening parens during definition. Good: `function foo ()` Bad: `function foo()`

- event.ts#getProduct
  - updateTime should be a `number` or otherwise more strongly typed
  - updateTime = 0 may be an edge case, simple enough to address

- split Quakeml and QuakemlEvent to separate files
  - https://angular.io/guide/styleguide#rule-of-one

- xml2json
  - Maybe check `Array.isArray(obj[nodeName])` rather than `typeof obj[nodeName].push === 'undefined'`
