### ISSUE TITLE
ShakeMap enhancements

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#820]
Don't repeatedly look up same values in template
Use formatter for formatting
avoid giant ternaries
https://github.com/usgs/earthquake-eventpages/pull/815/files#diff-24beddba4950363333be007973f02238R17

**Comment by emartinez-usgs** [comment]
Prefer dot notation for object dereferencing.

Several values should still be cached for repeated lookups. For example (as corrected)...
```
      <dl class="description-table" *ngIf="smProcessing.miscellaneous as miscellaneous">

        <ng-container *ngIf="miscellaneous.bias_max_mag as biasMaxMag">
          <dt>Max magnitude to compute bias</dt>
          <dd>{{ biasMaxMag }}</dd>
        </ng-container>
        ...
```
> Note: Free to use `let` or `as` syntax.

Why mixing camel and underscore separators? For example, "gmm", "ground_motion_modules", and "groundMotionModules". Be consistent.

Typo in "Ground Mation"

Why the table header translations for some but not all values?

Abbreviations should be wrapped in `<abbr>` with title text.

SA labels (eg. `SA(0.3)`) should include units. Typically `s`, but sometimes we (USGS) mix between `s` and `Hz`, so it is worth including.

Watch whitespace for coding standards.
Function _definitions_, include a space between function name and opening parenthesis
```
function getFoo () {
  return this.foo;
}
```
Function _calls_ do not include a space between function name and opening parenthesis
```
const foo = obj.getFoo();
```

Do not use built-in date pipe. We have specific date formats for web page display.

Event location is meant for event objects. Probably refactor eventLocation to use some other type of location pipe that directly accepts latitude/longitude. Use this latter pipe when working with non-event objects.

Pipes should not output HTML characters (updates required), and there should be no need for `[innerHTML]="value | pipe"`.

**Comment by dslosky-usgs** [comment]
Thanks for the feedback @emartinez-usgs, changes are underway!

I'm only using header translations in tables where the value in the first column acts as a header for the row, using the production event pages as a guide for translation. The values slipping through are either ones that I've missed or aren't being used in the production event pages.

Underscore separators are used in the info.json generated by shakemap; should I really adopt this convention for the whole metadata component? Maybe I can convince the shakemap guys to generate this product with camel casing instead...

**Comment by emartinez-usgs** [comment]
- Date pipe currently parses a `Date` object as a DateTime string. Maybe this should be a "DateTime" pipe. Or maybe it can be further parameterized to do date, time, or datetime?

- Wrapper `div` in input component HTML seems unnecessary. Just move `*ngIf` to `mat-expansion-panel`

- Some more caching opportunities eg...
```html
  <div class="input column" *ngIf="metadata.input as input">
    <h2>Input</h2>
    <shakemap-input [smInput]="input"></shakemap-input>
  </div>
```

- When wrapping lines exceeding the 80 character threshold, continuation lines are indented twice (4 spaces total) from the left indent of the first line. For example:
```html
<mat-cell [attr.role]="'rowheader'"
    [class.mat-cell]="false"
    class="mat-header-cell"
    *matCellDef="let groundMotion">
  <ng-container>...</ng-container>
  ...
</mat-cell>
```
> We should probably establish an ordering for attributes in HTML like this. Typically we've been putting `*ngIf` on the line with the opening tag, and other attributes subsequently, but we don't have a full rule for this yet.

- *Question* : Typically if a value is not provided by the product provider, we do not omit the label that might otherwise be visible. Instead, we include the label and the value is rendered as our default empty value, currently a dash `&ndash;` (probably swap to unicode equivalent). We do this so the interface is consistent and users do not as "Where is the 'X' value listed?". Is there a need for ShakeMap to behave differently? 

- There should not be a space between the degree value and the degree unit symbol (eg. output map information)

- There should be a space between a period value and the units "s". eg. `SA(0.3 s)`

- Title text should use SI units `s` rather than spelling out `seconds` (I know, it seems weird to use an abbreviation in the title text for an abbreviation).

- Using vertical whitespace for readability is fine, but don't overdue it. For example, this seems a bit overly spaced:
```html
<mat-cell *matCellDef="let module">

  {{ module.module }}

</mat-cell>
```
> We don't have a good rule here either. It's highly subjective so I'm not going to be too picky here.

- *Question*: Should processing maps be readonly or private even?

**Comment by emartinez-usgs** [comment]
### Coding Standards
- Continuation lines get indented two-levels (2 spaces per level) from primary line left edge
```html
        <!-- Not preferred -->
        <dd *ngIf="eventInfo.magnitude as mag;
                      else missingData">
        <!-- Preferred -->
        <dd *ngIf="eventInfo.magnitude as mag;
            else missingData">
        <!-- Or in this case, why wrap ... -->
        <dd *ngIf="eventInfo.magnitude as mag;  else missingData">
```

**Comment by dslosky-usgs** [comment]
@emartinez-usgs I was copying the html out of your comment to respond to you... when I accidentally deleted your comment... Sorry about that, here's the original

```html
        <!-- Not preferred -->
        <dd *ngIf="eventInfo.magnitude as mag;
                      else missingData">
        <!-- Preferred -->
        <dd *ngIf="eventInfo.magnitude as mag;
            else missingData">
        <!-- Or in this case, why wrap ... -->
        <dd *ngIf="eventInfo.magnitude as mag;  else missingData">
```

**Comment by dslosky-usgs** [comment]
In this case, I thought the wrapped `*ngIf` statement should be indented twice from the start of the statement, instead of the start of the line. This would help with readability of other properties were present.

```html
        <!-- Indented from start of line  -->
        <dd *ngIf="eventInfo.magnitude as mag;
             else missingData"
             class="class-name">

        <!-- How I did it -->
        <dd *ngIf="eventInfo.magnitude as mag;
                                    else missingData"
             class="class-name">

        <!-- Probably better? -->
        <dd *ngIf="eventInfo.magnitude as mag;
                      else missingData"
             class="class-name">
```

What do you think @emartinez-usgs?
