### ISSUE TITLE
ShakeMap Pin

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#847]
ShakeMap Pin

**Comment by emartinez-usgs** [comment]
- Do not add a "badge" to all the pins. I think either ...
  - Conditionally add a badge to the header section if a badge input is provided
  - Just specify the title as `card-title` input and provide the element as a child
- Badge styles should not encroach on pin content (note the SM image is slightly smaller than the other map images).
- The SM pin and generic interactive pin now look largely the same. Can we consider refactoring one of these? @wald-usgs might have some thoughts here.
  - Should the SM pin zoom to the overlay extent?
  - Should the interactive pin maybe not include SM contours?
  - Other ideas?
- Why are you aliasing `*ngIf="product as prod"` ?
- Since pin is authoritative only, probably okay to use the `event.properties.mmi` value for the pin, then no need to fetch the product. If fetching product, probably use the `getProduct:shakemap` pipe
