### ISSUE TITLE
Pager XML Service

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#893]
Read PAGER xml
Download, parse PAGER xml
See QuakeML service

**Comment by emartinez-usgs** [comment]
Parsing error. Consider event `us2000ar20`. Note the exposure table on the current event pages shows MMI `I` and `II - III` both have an asterisk indicating the mapped data are incomplete.

The parsed data structure in this implementation incorrectly claims the data are complete for `II-III`. I think this is because `'0' && '1'` evaluates to `'1'`. This needs to be corrected.

Also, number should be numbers, booleans should be booleans (etc...) in the parsed data structure.
