### ISSUE TITLE
Create ground-failure overlays

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#918]
From product properties
A landslides overlay 
liquefaction overlay

**Comment by ehunter-usgs** [comment]
https://dev01-earthquake.cr.usgs.gov/earthquakes/eventpage/us2000dvwq#executive

From the product properties it looks like there are min/max bounds for latitude/longitude. I have to assume that this is for the raster image that will be the overlay on the static map? I have a few questions:
 - I thought we were going to use actual data not raster images?
 - What are the titles for the overlays?
 - Should the map bounds match the overlay bounds? (the overlay bounds are not quite the same for both landslide and liquefaction)
 - Which model do I use for the liquefaction overlay? (will there always be a "liquefaction-overlay" property)
 - Which model do I use for the landslide overlay? (there is no "landslide-overlay" property)

**Comment by llastowka-usgs** [comment]
@emthompson-usgs ?  Just checking if you need/want to comment

**Comment by emthompson-usgs** [comment]
I'm not sure what you mean by "actual data." All of the ground failure information we want to show in the map is raster data for this product. We can discuss in person if this is still confusing. 

For overlay titles, would you like to hard code that or should I add them as product properties? Should they also go info.json?

Since the extents of the two grids are slightly different, I'd suggest just picking one for now (e.g., landslides) until we can come up with something better. They shouldn't really be significantly different though. 

There should always be one `liquefaction-overlay` property and it will always point to the preferred model for the interactive map. 

The lack of a `landslide-overlay` property was a mistake on my part. I fixed it and just resent the product. To confirm you received it, it has a timestamp of 1523917360141.

**Comment by jmfee-usgs** [comment]
My thoughts:

- Refactor the AsynchronousGeoJSON into AsynchronousLayer, and in the overlay create a L.LayerGroup during construction; then in onAdd load info.json and find the `preferred` landslide or liquefaction model (as appropriate) and create an ImageOverlay to be added to the LayerGroup.

- Kate/Eric can provide titles, my guess is "Landslide" and "Liquefaction" for now; until there are other Landslide/Liquefaction info sources.

- the Overlay bounds (angular overlay interface, rather than image overlay which comes from info.json) should use the product properties minimum-latitude etc.

**Comment by emthompson-usgs** [comment]
I talked to @ehunter-usgs via chat about titles, and we settled on "Liquefaction Estimate" and "Landslide Estimate" for now but are open to changes. 

I was under the impression that you could get the overlay file directly from the product properties without having to load info.json but I'm probably missing something.

**Comment by jmfee-usgs** [comment]
It needs to be loaded from info.json if we will ever display non-preferred models on the event pages.  (there are only one set of product properties)

**Comment by jmfee-usgs** [comment]
need additional test coverage.
