### ISSUE TITLE
Shakemap map overlays pipe

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#926]

**Comment by emartinez-usgs** [comment]
What is the use-case/difference between `shakemap-overlays.pipe.ts` and `shakemap-map-overlays.pipe.ts`. Looking at the `region-info-overlays.pipe.ts` as an example it seems that is much simpler but maybe it is less like the `interactive-map-overlays-pipe.ts` ?

**Comment by dslosky-usgs** [comment]
Yeah, `shakemap-map-overlays.pipe.ts` is doing the same job as `interactive-map-overlays-pipe.ts`but specifically for the ShakeMap product view. Any map that combines overlays from multiple pipes will use something like this. Shakemap will use a second "advanced" layers pipe with all the PSA layers and such that we don't want on the interactive map.

**Comment by jmfee-usgs** [comment]
I think we do want those layers on the interactive map, just not enabled by default.

We should probably discuss more.

**Comment by jmfee-usgs** [comment]
As we discussed this morning, since Shakemap contours are already part of the interactive map pin, update the pin to be something like:


**Intensity**
  MMI
**Perceived Shaking**
  SHAKING
**Potential Damage**
  DAMAGE

where shaking and damage correspond to the mmi value in the legend:
https://pubs.usgs.gov/fs/fs-087-03/FS-087-03-508.pdf
